/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wentong_demo_jni_DataSynchronizer */

#ifndef _Included_com_wentong_demo_jni_DataSynchronizer
#define _Included_com_wentong_demo_jni_DataSynchronizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wentong_demo_jni_DataSynchronizer
 * Method:    syncData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wentong_demo_jni_DataSynchronizer_syncData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
